### ISSUE TITLE
Interactive Post-it

### ISSUE THREAD

**Issue by mathieuLivebardon** [VCityTeam/UD-Imuv#111]
- [ ] Select a tool
- [ ] Integrate the tool in the client side
- [ ] Create gameobject that the player can interact with (in the studios rooms)

**Comment by ggesquiere** [comment]
Please have a look to Mural and Miro

**Comment by valentinMachado** [comment]
mural and miro are whiteboard see this issue https://github.com/VCityTeam/UD-Imuv/issues/31

**Comment by valentinMachado** [comment]
https://github.com/VCityTeam/UD-Imuv/pull/136
