### ISSUE TITLE
Update the images of the exhitbit show and provide online direct access

### ISSUE THREAD

**Issue by EricBoix** [VCityTeam/UD-Imuv#116]
- Contact the exhibit organizer (Stéphane A.?) and 
    - [x] collect the updated pictures for the exhibit
    - [x] Offer to collect a frame that would be an image of text presenting the exhibit 
    - [x] Ask where the new pictures should be placed/located in the exhibition room
 - [x] Update the pictures of the exhibit with the new content
 - [x] Provide an URL that enables a simplified access to the exhibit room
 - [x] Provide instructions for the visitor: where he should walk to, what interactions are possible
        (as a popup?)

## Options
 - [x] Check whether an exhibit picture can be associated with a world (AFK) coordinates
 - [x] When a picture of the exhibit is selected the position should be depicted in the city map overview

**Comment by mathieuLivebardon** [comment]
https://im7.ezgif.com/tmp/ezgif-7-4717a1620f.gif

**Comment by mathieuLivebardon** [comment]
Summary of point with SAU: 
- Introductory text: welcome / cut into small pieces / associated with a set of photos?
- Map of movements.
- Popup: Full screen on photos + text + location on map (place).
- Talk about the physical exhibition in the mail.

I will work about the Popup until I receive the details I need.
