### ISSUE TITLE
Server deployment

### ISSUE THREAD

**Issue by valentinMachado** [VCityTeam/UD-Imuv#12]
- [x] Find hosting provider : OVH 
- [x] Choose a technical offer : VPS [Comfort](https://www.ovhcloud.com/fr/vps/compare/) + Domain name (labeximu.fr ?)
- [x] Obtain a quote and order the products
- [x] Deploy IMUV application on VPS (ssh + docker)
- [ ] Wrap the application into a HTTPS server (nginx)

**Comment by valentinMachado** [comment]
contact ovh to see with them if they can handle the deplment of the bbb server

**Comment by valentinMachado** [comment]
audio and video not allow when deploy on rict2
bad bbb url are provide to client

**Comment by valentinMachado** [comment]
an OVH offer has been choosen https://www.ovhcloud.com/fr/web-paas/ (solution start at 30 euros per month) and has been transfered to LabexIMU

**Comment by ggesquiere** [comment]
Please have a discussion with Clarisse in LabEx IMU. They may need a possible server (like OVH) to share geographic data.

**Comment by valentinMachado** [comment]
I have met members of la coopérative des internets (https://www.lacooperativedesinternets.fr/) they could have hosting solution. I am in contact with them to determine what is the proper solution.

**Comment by valentinMachado** [comment]
> Please have a discussion with Clarisse in LabEx IMU. They may need a possible server (like OVH) to share geographic data.

Hosting another application should be not a problem. From what I have understood the other application requires a new port expose + some data storage + some bandwith to serve the web content.

**Comment by mathieuLivebardon** [comment]
Deploy on https://imuvirtuel.fr
