### ISSUE TITLE
different lod of the city 

### ISSUE THREAD

**Issue by valentinMachado** [VCityTeam/UD-Imuv#200]
Have a meeting with @LorenzoMarnat  to discuss what's possible.

Look for even more performance (the continuation of "[refine](https://github.com/VCityTeam/UD-Imuv/pull/188)"). The 3D city under the Flying Campus with less detail could save FPS and make moving with the avatar more fluid.

**Comment by LorenzoMarnat** [comment]
I think (one of) the main problem right now is the relief. The relief geometry is hightly detailled (millions of triangles) while we don't see those details most of the time. There is no existing solution in Py3DTilers to create relief LODs. Maybe we could use some glTF simplication tools to reduce the number of triangles. The process would be:

- Use [3d-tiles-tools](https://github.com/engineerhe/3d-tiles-tools) to tranform tiles into glb models
- Use simplication tools from MeshLab/Blender on the glb models
- Use 3d-tiles-tools to transform glb models into tiles

**Comment by valentinMachado** [comment]
we have finally replaced 3dtiles relief by an elevation layer see https://github.com/VCityTeam/UD-Imuv/pull/230

**Comment by LorenzoMarnat** [comment]
Sounds good

Note that you can also use the IGN color layer (and keep the same elevation layer)
```json
  "background_image_layer": {
    "url": "https://wxs.ign.fr/choisirgeoportail/geoportail/r/wms",
    "name": "GEOGRAPHICALGRIDSYSTEMS.PLANIGNV2",
    "version": "1.3.0",
    "format": "image/jpeg",
    "layer_name": "Base_Map",
    "maxSubdivisionLevel": 5
  },
```
![image](https://user-images.githubusercontent.com/32875283/180455542-4f84f12b-df44-4dba-8ef5-4cf939e4baaf.png)
