### ISSUE TITLE
Minimap when you have jump in the city

### ISSUE THREAD

**Issue by mathieuLivebardon** [VCityTeam/UD-Imuv#211]
*Integrate a widget which give the position of the avatar in the city.*
>*A widget minimap exists in itowns but only the GlobeView is supported for now.*

EDIT : 
Use a map generate with a tool (QGIS ?) and make our own minimap widget.

**Comment by valentinMachado** [comment]
I found a map here https://fr.m.wikipedia.org/wiki/Fichier:Lyon_et_ses_arrondissements_map.svg
