### ISSUE TITLE
Jitsi's usage improved

### ISSUE THREAD

**Issue by mathieuLivebardon** [VCityTeam/UD-Imuv#214]
- Password
- Autojoin
- Name is automatically the same between Jitsti and IMUV
- Creation of areas of discussion
- ...

**Comment by valentinMachado** [comment]
Can we close this ? @mathieuLivebardon

**Comment by mathieuLivebardon** [comment]
> Can we close this ? @mathieuLivebardon
I think it's good, only password part is not already implemented. I will create an issue.
