### ISSUE TITLE
BBB server deployment

### ISSUE THREAD

**Issue by valentinMachado** [VCityTeam/UD-Imuv#22]
Integrate big blue button to allow vocal chat between client

ref : https://bigbluebutton.org/

**Comment by valentinMachado** [comment]
Find where to deploy bbb server.

1 - A server of bbb is hosted at lyon2 can we use this server ?
2 - If not bbb server have to be considered in the choice of the server where to deploy UD-Imuv [minimum requirements](https://docs.bigbluebutton.org/2.3/install.html#minimum-server-requirements) 

At the same time begin with a local server to test the integration of the web client (greenlight) in UD-IMUV client.

**Comment by valentinMachado** [comment]
api doc bbb
https://docs.bigbluebutton.org/dev/api.html

**Comment by valentinMachado** [comment]
docker inspect <container-id> yields many informations among which the
    port mappings, volumes used...
    For example: docker inspect <container-id> -f '{{json .State.OOMKilled}}'
    will return true if the running process wall killed because it ran
    Out Of Memory.

lol

**Comment by valentinMachado** [comment]
docker inspect <container-id> yields many informations among which the
    port mappings, volumes used...
    For example: docker inspect <container-id> -f '{{json .State.OOMKilled}}'
    will return true if the running process wall killed because it ran
    Out Of Memory.

could be a clue for the server deployment which did not succeed due to a wrong port mapping between public port and docker ports

**Comment by mathieuLivebardon** [comment]
oooooooooooooooooooooold
