### ISSUE TITLE
Intregration of the webdoc

### ISSUE THREAD

**Issue by mathieuLivebardon** [VCityTeam/UD-Imuv#225]
Integrated the web documentary developed in the TIGA project. This would provide an interactive model.

**Comment by valentinMachado** [comment]
Since the webdoc is not going to be publish should we close this @mathieuLivebardon ?

**Comment by mathieuLivebardon** [comment]
> Since the webdoc is not going to be publish should we close this @mathieuLivebardon ?

We can leave this issue aside. This is a good use case idea, while waiting to see what happens to the webdoc and if the software base is recovered for another project.
