### ISSUE TITLE
We can't go back to the Jitsi room in conference room

### ISSUE THREAD

**Issue by mathieuLivebardon** [VCityTeam/UD-Imuv#232]
When we leave the call Jitsi, there is no possibility to go back. (actually, we can come and go in the conference room ^^)

**Comment by valentinMachado** [comment]
Apparently in the last version it could be configured
https://github.com/jitsi/jitsi-meet/blob/a7c653bc30156ec6ae7e3f67b28fffb07f3e79de/interface_config.js#L71

Not sure if it should be done on the client or server side as explained here => https://github.com/jitsi/jitsi-meet/issues/7354
