### ISSUE TITLE
Create a fonctional schema of UD-IMUV application

### ISSUE THREAD

**Issue by valentinMachado** [VCityTeam/UD-Imuv#24]

**Comment by Didier-Intervenant** [comment]
qu'est-ce que entends par là ! "fonctional schema of UD-IMUV application" !! est-ce que l'on peut t'aider  ?

**Comment by valentinMachado** [comment]
https://github.com/VCityTeam/VCity/blob/master/Projects/FlyingCampus_IMUV/Project_Page_FlyingCampus_IMUV.md#roadmap2022
