### ISSUE TITLE
Create an circular icon in black and white imuv

### ISSUE THREAD

**Issue by valentinMachado** [VCityTeam/UD-Imuv#246]
![image](https://user-images.githubusercontent.com/34244904/187429746-03d5cf2f-e8e1-40ce-a1cd-8dc043c8048e.png)
Create an IMUV icon in the same style as media button to place it at the place of the red face drew.

**Comment by mathieuLivebardon** [comment]
![LogoTransparent40pxV3](https://user-images.githubusercontent.com/34244904/188876194-d147df49-a06e-4223-a7e5-0181b23c4504.png)
Done ♾️
