### ISSUE TITLE
Describe how refresh pass work in Imuv

### ISSUE THREAD

**Issue by valentinMachado** [VCityTeam/UD-Imuv#272]

**Comment by mathieuLivebardon** [comment]
You may use mermaidjs in order to create a sequence/loop diagram https://mermaid-js.github.io/mermaid/#/sequenceDiagram?id=loops

**Comment by valentinMachado** [comment]
documentation in ud-viz https://github.com/VCityTeam/UD-Viz/compare/doc-gameview?expand=1

**Comment by mathieuLivebardon** [comment]
> documentation in ud-viz [VCityTeam/UD-Viz#433](https://github.com/VCityTeam/UD-Viz/pull/433)

OUTDATED since ud-viz 3.0
