### ISSUE TITLE
Whiteboard

### ISSUE THREAD

**Issue by Didier-Intervenant** [VCityTeam/UD-Imuv#31]
- [x] Select a Whiteboard tool (e.g. [Whitebophir](https://github.com/lovasoa/whitebophir) ~~or [BBB-Whiteboard](https://support.bigbluebutton.org/hc/en-us/articles/1500005316822-Use-the-multi-user-whiteboard)~~ or [Excalidraw](https://excalidraw.com/))?
- [x] Integrate the tool in the client side
- [x] Create gameobject that the player can interact with (in the studios rooms)

Optionnal:
- [ ] Is it possible to use whiteboards to share a player screen in the game ?

**Comment by mathieuLivebardon** [comment]
https://github.com/lovasoa/whitebophir

**Comment by ggesquiere** [comment]
Please have a look to the possible license of dependances
Please see if BBB can be used for deploying the whiteboard fonctionality

**Comment by valentinMachado** [comment]
We are gonna try to deploy our own BBB server on OVH back end, if we do not succeed we could give a try to implement the whitebophir whiteboard since its dependances seems okay to be used by us.

**Comment by mathieuLivebardon** [comment]
https://github.com/jitsi/jitsi-meet/issues/5295
