### ISSUE TITLE
Popup images room expo

### ISSUE THREAD

**Issue by Didier-Intervenant** [VCityTeam/UD-Imuv#33]
Exhibition room [14] photos + extended explanation> Pop-Up / Map situation

**Comment by Didier-Intervenant** [comment]
When you click on the exposed photo a popup is displayed showing the place where the photo was taken in Lyon

**Comment by mathieuLivebardon** [comment]
![ksnip_20211122-112109](https://user-images.githubusercontent.com/34244904/142844349-a5fde93a-587e-4d59-b256-bf177d31c7fe.png)
