### ISSUE TITLE
interactive signage of current projects from observation platforms

### ISSUE THREAD

**Issue by Didier-Intervenant** [VCityTeam/UD-Imuv#37]

**Comment by valentinMachado** [comment]
![Capture d’écran de 2021-10-12 11-40-03](https://user-images.githubusercontent.com/14295096/136932565-2963ccdc-5232-4f32-98f6-c795e3ca2c85.png)

**Comment by valentinMachado** [comment]
what should be display for each platform ?
provide a 3D model of the red pin

**Comment by mathieuLivebardon** [comment]
Redesign and standardization of collision event management
Look at this PR : https://github.com/VCityTeam/UD-Imuv/pull/94

**Comment by mathieuLivebardon** [comment]
Test to display a billboard

**Comment by mathieuLivebardon** [comment]
Popup :

![popup](https://user-images.githubusercontent.com/34244904/146952153-9b5f3c45-4bb1-494d-b2c9-806504ad67ab.PNG)

Project1             |  Project2
:-------------------------:|:-------------------------:
![billboard1](https://user-images.githubusercontent.com/34244904/146952128-c63d2105-9fc1-46eb-9a31-01c11d464123.PNG) | ![billboard2](https://user-images.githubusercontent.com/34244904/146952144-336e1b94-7a2a-49a1-9752-6ac2930043ea.PNG)
