### ISSUE TITLE
Overlapping portal mini map

### ISSUE THREAD

**Issue by valentinMachado** [VCityTeam/UD-Imuv#379]
Some studio portal are overlapping, think a solution to avoid this behavior.
Maybe creating a select element when to portal are too close of eachother

**Comment by mathieuLivebardon** [comment]
We can think of an element like hoverable dropdown.

**Comment by mathieuLivebardon** [comment]
We need to look into this
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context
