### ISSUE TITLE
Procedural butterfly

### ISSUE THREAD

**Issue by Didier-Intervenant** [VCityTeam/UD-Imuv#40]

**Comment by mathieuLivebardon** [comment]
![ksnip_20211103-094449](https://user-images.githubusercontent.com/34244904/140031119-c89a9c85-9b8a-4458-ad28-8e34beb825f4.png)

Butterfly in Sprites Object without animation

**Comment by mathieuLivebardon** [comment]
![butterfly1stAnimation](https://user-images.githubusercontent.com/34244904/140041429-11014dbe-6339-451f-8dd9-6b796d4d44b4.gif)
First Animations

**Comment by mathieuLivebardon** [comment]
![](https://user-images.githubusercontent.com/34244904/140484187-fc7005cf-f87c-4c05-a7fd-35d09bd467e4.gif)

**Comment by Didier-Intervenant** [comment]
y-a-t-il un moyen pour afficher 2 sprites  par particule en les alternants (ailes ouvertes / ailes fermées) ?

**Comment by mathieuLivebardon** [comment]
> y-a-t-il un moyen pour afficher 2 sprites par particule en les alternants (ailes ouvertes / ailes fermées) ?

Oui je pense qu'il y a moyen je vais tester et j'envoie le resultat

**Comment by mathieuLivebardon** [comment]
![butterflyAnimation2Sprites](https://user-images.githubusercontent.com/34244904/140535084-90b27b12-a635-41aa-bccf-973355125d50.gif)
Animation 2 Sprites

**Comment by Didier-Intervenant** [comment]
super !! est-ce que tu peux désynchroniser l'animation ? >CAD faire que les papillons ne ferment pas tous les ailes au même moment . il pourrait il y avoir une petite variable sur la duration !! je suis un peu chiant ! non ?

**Comment by mathieuLivebardon** [comment]
D'accord très bien je vais désynchroniser l'animation avec une variable aléatoire 😄

**Comment by mathieuLivebardon** [comment]
![butterfly_async](https://user-images.githubusercontent.com/34244904/141758085-b89cbf63-8f6a-4bda-88b1-178993f4878a.gif)
