### ISSUE TITLE
Trophée Jumeaux Numériques

### ISSUE THREAD

**Issue by mathieuLivebardon** [VCityTeam/UD-Imuv#407]
Prepare to participate:

- [x] Registration
- [x] Scenario
- Video
  - [x] Record
  - [x] Editing
- [x] Application form

**Comment by mathieuLivebardon** [comment]
Scenario :

1. Show a classical digital twin.
2. Arrived at the island!!!
3. Discussion between several people under a parasol. Idea of project.
4. See the 3D model of Lyon with several people.
5. Make a conference with a master of conference who chooses the area of the new project.
6. Creation of a studio
7. Work on the project in the studio
8. Conclusion of the project by adding in the 3D environment:
   1. Display panels
   2. Advertising (=links/media)
   3. Images in the showroom
9. END / CREDITS

| Locations / Features | Key  |
| -------------------- | ---- |
| Itowns view          | 1    |
| Island               | 2, 8 |
| Jitsi                | 3    |
| Jumping in the city  | 4    |
| Conference Room      | 5    |
| Editor               | 6, 8 |
| Studios              | 7    |
| Exhibit Hall         | 8    |
| Signboards           | 8    |
| Advertising          | 8    |

**Comment by mathieuLivebardon** [comment]
# Préparation de la candidature vidéo :
> Partie "fonctionnement de l'application":


[partagez votre écran pour vous appuyer sur un schéma d’architecture ou arborescence du projet (image fixe ou animée)]

### Présentez les principales briques et principaux modules


Ce qu'on doit enregistrer pour la vidéo:

- Image d'une arborescance globale
- Liens entre les briques (en gros : THREE -> Itowns -> UD-Viz -> IMUV).
- Zoom sur les différentes parties avec de breves explications.
- Liens des sites :
    - THREE.js - https://threejs.org/
    - Itowns (IGN) - https://www.itowns-project.org/
    - UD-Viz (LIRIS) - https://ud-viz.vcityliris.data.alpha.grandlyon.com/
    - Jitsi - https://jitsi.org/
    - Whitebophir - https://github.com/lovasoa/whitebophir
    - Parse - https://parseplatform.org/
    - Mongodb - https://www.mongodb.com/fr-fr


Texte :

Pourquoi on a choisi ces briques, parce que la plupart sont open-source. Lien fort avec UD-Viz, développé en interne au LIRIS. L'idée est de mettre à disposition l'outil dans le monde de la recherche et permettre l'utilisation par différents acteurs privé et publique qui peuvent collaborer à l'élaboration du projet.

### Détaillez les principales solutions logicielles ou technologiques utilisées et les développements spécifiques réalisés

Ce qu'on doit enregistrer pour la vidéo:

- Image qui montre un front-end back-end
- Le github
- Image du jeu

Texte:

La solution logicielle proposée prend la forme d'une application web composé d'un front-end (javascript + webgl) et d'un back-end (nodejs) spécifique. C'est un outil collaboratif (multijoueur) immersif sous la forme d'un campus numérique dans un monde 3D persistant sur le web. 
Tout est disponible sur la plateforme Github (https://github.com/VCityTeam/UD-Imuv/) où on peut retrouver les deux projets npm (front et back). Participation au développement d'UD-Viz.


###  Précisez sur quels référentiels techniques, normes ou standards vous appuyez-vous (consortiums, groupes de travail) pour mettre en place le projet ?

Ce qu'on doit enregistrer pour la vidéo:

- Site du Labex
- Site du LIRIS
- Site de VCity 


Texte:

Projet initié par le Labex IMU. Collaboration avec les membres de la plateforme UD-SV/VCity (LIRIS). Responsabilité scientifique (JYT et GGE). Méthode agile (itératif), milestone trimestriel. Idée originale de JYT, GGE et DCH. Le projet à commencé avec Didier CHANFRAY, Yael BARROZ, Valentin MACHADO et Mathieu LIVEBARDON. Et ajourd'hui poursuivi en binome par NOUS.


###  Montrez ensuite les principales fonctions de votre jumeau numérique, le processus collaboratif, les outils d'analyse, la valorisation des données, etc.

Ce qu'on doit enregistrer pour la vidéo:
- Gameplay
- Fonctionnalités
- Voir Scénario (en haut)


Texte:

Commenter le gameplay. 

###  Indiquez d’où proviennent les données utilisées ? Par qui et comment sont collectées les données initiales et actualisées, à quelle fréquence et où sont-elles hébergées ?

Ce qu'on doit enregistrer pour la vidéo:

- Py3dtiler
- Site du GrandLyon
- Site de l'IGN (https://geoservices.ign.fr/telechargement)
- Image de l'ile / avatar / **ZEPPELYON** ouvert dans blender

Texte:

| Type                                                | Provenance      | Actualisé            | Hebergé           |
| --------------------------------------------------- | --------------- | -------------------- | ----------------- |
| Elecation Layer                                     | data grand lyon | //                   | //                |
| Fond de carte                                       | IGN             | //                   | //                |
| Lignes de bus, velov et zones humides               | data grand lyon | //                   | //                |
| 3Dtiles                                             | ?               | py3dtilers (Lorenzo) | VPS OVH           |
| Modeles 3D (iles, salles, avatar, zeppelin, spiral) | Yael Barroz     | //                   | VPS OVH           |
| Modeles 3D (souris)                                 | Internet        | //                   | VPS OVH           |
| Donnée utilisateur                                  | imuvirtuel.fr   | //                   | VPS OVH (mongodb) |



Externe et interne. Externe : IGN, data grand lyon Interne : py3dtiler, gltf (yaël) 





###  Indiquez à nouveau qui sont les gestionnaires, utilisateurs et les bénéficiaires. Quels sont leurs rôles dans le fonctionnement ?

La communauté open-source, les acteurs urbains, les partenaires d'IMU, les citoyens intéressés par les questions d'urbanisme, le monde de la recherche **urbaine**.

**Comment by valentinMachado** [comment]
# Préparation de la candidature vidéo :

fondu noir musique des mii (voir avec ACH pour les droits)
> Partie "fonctionnement de l'application":


[partagez votre écran pour vous appuyer sur un schéma d’architecture ou arborescence du projet (image fixe ou animée)]

### Présentez les principales briques et principaux modules

IMUV ca ressemble a ça (image qui va monter tout les briques + modules) faisons un next slide sur three.js.
three.js JavaScript 3D Library. ensuite itowns A Three.js-based framework written in Javascript/WebGL for visualizing 3D geospatial data. ud-viz qui fait partie de la plateforme de recherche udsv. UD-SV (Urban Data Services and Visualization) is a set of software components dedicated to the experimentation, exchange and sharing of both knowledge and tools for the concrete handling of urban/city data (that are based on the CityGML data model). voila
les briques on utilise wbo comme outil de tableau blanc, jitsi pour la visio et parse couplé a mongo pour l'authentification. tous ces modules et briques sont opensource ou freeuse. 
Pourquoi on a choisi ces briques, parce que la plupart sont open-source. Lien fort avec UD-Viz, développé en interne au LIRIS. L'idée est de mettre à disposition l'outil dans le monde de la recherche et permettre l'utilisation par différents acteurs privé et publique qui peuvent collaborer à l'élaboration du projet.

Ce qu'on doit enregistrer pour la slide:

- Image d'une arborescance globale
- Liens entre les briques (en gros : THREE -> Itowns -> UD-Viz -> IMUV).
- Zoom sur les différentes parties avec de breves explications.
- Liens des sites :
    - THREE.js - https://threejs.org/
    - Itowns (IGN) - https://www.itowns-project.org/
    - UD-Viz (LIRIS) - https://ud-viz.vcityliris.data.alpha.grandlyon.com/
    - Jitsi - https://jitsi.org/
    - Whitebophir - https://github.com/lovasoa/whitebophir
    - Parse - https://parseplatform.org/
    - Mongodb - https://www.mongodb.com/fr-fr

### Détaillez les principales solutions logicielles ou technologiques utilisées et les développements spécifiques réalisés

Ce qu'on doit enregistrer pour la vidéo:

- Image qui montre un front-end back-end
- Le github
- Image du jeu

Texte:

toutes les briques et modules enoncé precedement sont necessaire pour assurer le bon fonctionnement de notre solution logiciel imuv.
La solution logicielle proposée prend la forme d'une application web composé d'un front-end (javascript + webgl) et d'un back-end (nodejs) spécifique. C'est un outil collaboratif (multijoueur) immersif sous la forme d'un campus numérique dans un monde 3D persistant sur le web. 
Tout est disponible sur la plateforme Github (https://github.com/VCityTeam/UD-Imuv/) où on peut retrouver les deux projets npm (front et back). Participation au développement d'UD-Viz.


###  Précisez sur quels référentiels techniques, normes ou standards vous appuyez-vous (consortiums, groupes de travail) pour mettre en place le projet ?

Ce qu'on doit enregistrer pour la vidéo:

- Site du Labex
- Site du LIRIS
- Site de VCity 


Texte:

Projet initié par le Labex IMU. Collaboration avec les membres de la plateforme UD-SV/VCity (LIRIS). Responsabilité scientifique (JYT et GGE). Méthode agile (itératif), milestone trimestriel. Idée originale de JYT, GGE et DCH. Le projet à commencé avec Didier CHANFRAY, Yael BARROZ, Valentin MACHADO et Mathieu LIVEBARDON.


###  Montrez ensuite les principales fonctions de votre jumeau numérique, le processus collaboratif, les outils d'analyse, la valorisation des données, etc.

Ce qu'on doit enregistrer pour la vidéo:
- Gameplay
- Fonctionnalités
- Voir Scénario (en O)


Texte:quand on aura la vidéo

Commenter le gameplay. 

###  Indiquez d’où proviennent les données utilisées ? Par qui et comment sont collectées les données initiales et actualisées, à quelle fréquence et où sont-elles hébergées ?

Ce qu'on doit enregistrer pour la vidéo:

- Py3dtiler
- Site du GrandLyon
- Site de l'IGN (https://geoservices.ign.fr/telechargement)
- Image de l'ile / avatar / **ZEPPELYON** ouvert dans blender

Texte:

| Type                                                | Provenance      | Actualisé            | Hebergé           |
| --------------------------------------------------- | --------------- | -------------------- | ----------------- |
| Elecation Layer                                     | data grand lyon | //                   | //                |
| Fond de carte                                       | IGN             | //                   | //                |
| Lignes de bus, velov et zones humides               | data grand lyon | //                   | //                |
| 3Dtiles                                             | cityGML data grand lyon        2018       | py3dtilers (Lorenzo) | VPS OVH           |
| Modeles 3D (iles, salles, avatar, zeppelin, spiral) | Yael Barroz     | //                   | VPS OVH           |
| Modeles 3D (souris)                                 | Internet        | //                   | VPS OVH           |
| Donnée utilisateur                                  | imuvirtuel.fr   | //                   | VPS OVH (mongodb) |



Externe et interne. Externe : IGN, data grand lyon Interne : py3dtiler, gltf (yaël) 





###  Indiquez à nouveau qui sont les gestionnaires, utilisateurs et les bénéficiaires. Quels sont leurs rôles dans le fonctionnement ?

La communauté open-source, les acteurs urbains, les partenaires d'IMU, les citoyens intéressés par les questions d'urbanisme, le monde de la recherche **urbaine**.

**Comment by valentinMachado** [comment]
> # Préparation de la candidature vidéo :
> > Partie "fonctionnement de l'application":
> 
> [partagez votre écran pour vous appuyer sur un schéma d’architecture ou arborescence du projet (image fixe ou animée)]
> 
> ### Présentez les principales briques et principaux modules
> Ce qu'on doit enregistrer pour la vidéo:
> 
> * Image d'une arborescance globale
> * Liens entre les briques (en gros : THREE -> Itowns -> UD-Viz -> IMUV).
> * Zoom sur les différentes parties avec de breves explications.
> * Liens des sites :
>   
>   * THREE.js - https://threejs.org/
>   * Itowns (IGN) - https://www.itowns-project.org/
>   * UD-Viz (LIRIS) - https://ud-viz.vcityliris.data.alpha.grandlyon.com/
>   * Jitsi - https://jitsi.org/
>   * Whitebophir - https://github.com/lovasoa/whitebophir
>   * Parse - https://parseplatform.org/
>   * Mongodb - https://www.mongodb.com/fr-fr
> 
> Texte :
> 
> Pourquoi on a choisi ces briques, parce que la plupart sont open-source. Lien fort avec UD-Viz, développé en interne au LIRIS. L'idée est de mettre à disposition l'outil dans le monde de la recherche et permettre l'utilisation par différents acteurs privé et publique qui peuvent collaborer à l'élaboration du projet.
> 
> ### Détaillez les principales solutions logicielles ou technologiques utilisées et les développements spécifiques réalisés
> Ce qu'on doit enregistrer pour la vidéo:
> 
> * Image qui montre un front-end back-end
> * Le github
> * Image du jeu
> 
> Texte:
> 
> La solution logicielle proposée prend la forme d'une application web composé d'un front-end (javascript + webgl) et d'un back-end (nodejs) spécifique. C'est un outil collaboratif (multijoueur) immersif sous la forme d'un campus numérique dans un monde 3D persistant sur le web. Tout est disponible sur la plateforme Github (https://github.com/VCityTeam/UD-Imuv/) où on peut retrouver les deux projets npm (front et back). Participation au développement d'UD-Viz.
> 
> ### Précisez sur quels référentiels techniques, normes ou standards vous appuyez-vous (consortiums, groupes de travail) pour mettre en place le projet ?
> Ce qu'on doit enregistrer pour la vidéo:
> 
> * Site du Labex
> * Site du LIRIS
> * Site de VCity
> 
> Texte:
> 
> Projet initié par le Labex IMU. Collaboration avec les membres de la plateforme UD-SV/VCity (LIRIS). Responsabilité scientifique (JYT et GGE). Méthode agile (itératif), milestone trimestriel. Idée originale de JYT, GGE et DCH. Le projet à commencé avec Didier CHANFRAY, Yael BARROZ, Valentin MACHADO et Mathieu LIVEBARDON. Et ajourd'hui poursuivi en binome par NOUS.
> 
> ### Montrez ensuite les principales fonctions de votre jumeau numérique, le processus collaboratif, les outils d'analyse, la valorisation des données, etc.
> Ce qu'on doit enregistrer pour la vidéo:
> 
> * Gameplay
> * Fonctionnalités
> * Voir Scénario (en haut)
> 
> Texte:
> 
> Commenter le gameplay.
> 
> ### Indiquez d’où proviennent les données utilisées ? Par qui et comment sont collectées les données initiales et actualisées, à quelle fréquence et où sont-elles hébergées ?
> Ce qu'on doit enregistrer pour la vidéo:
> 
> * Py3dtiler
> * Site du GrandLyon
> * Site de l'IGN (https://geoservices.ign.fr/telechargement)
> * Image de l'ile / avatar / **ZEPPELYON** ouvert dans blender
> 
> Texte:
> 
> Type	Provenance	Actualisé	Hebergé
> Elecation Layer	data grand lyon	//	//
> Fond de carte	IGN	//	//
> Lignes de bus, velov et zones humides	data grand lyon	//	//
> 3Dtiles	cityGML data grand lyon	py3dtilers (Lorenzo)	VPS OVH
> Modeles 3D (iles, salles, avatar, zeppelin, spiral)	Yael Barroz	//	VPS OVH
> Modeles 3D (souris)	Internet	//	VPS OVH
> Donnée utilisateur	imuvirtuel.fr	//	VPS OVH (mongodb)
> Externe et interne. Externe : IGN, data grand lyon Interne : py3dtiler, gltf (yaël)
> 
> ### Indiquez à nouveau qui sont les gestionnaires, utilisateurs et les bénéficiaires. Quels sont leurs rôles dans le fonctionnement ?
> La communauté open-source, les acteurs urbains, les partenaires d'IMU, les citoyens intéressés par les questions d'urbanisme, le monde de la recherche **urbaine**.



# Préparation de la candidature vidéo :

fondu noir musique des mii (voir avec ACH pour les droits)
> Partie "fonctionnement de l'application":


[partagez votre écran pour vous appuyer sur un schéma d’architecture ou arborescence du projet (image fixe ou animée)]

### Présentez les principales briques et principaux modules

IMUV ca ressemble a ça (image qui va monter tout les briques + modules) faisons un next slide sur three.js.
three.js JavaScript 3D Library. ensuite itowns A Three.js-based framework written in Javascript/WebGL for visualizing 3D geospatial data. ud-viz qui fait partie de la plateforme de recherche udsv. UD-SV (Urban Data Services and Visualization) is a set of software components dedicated to the experimentation, exchange and sharing of both knowledge and tools for the concrete handling of urban/city data (that are based on the CityGML data model). voila
les briques on utilise wbo comme outil de tableau blanc, jitsi pour la visio et parse couplé a mongo pour l'authentification. tous ces modules et briques sont opensource ou freeuse. 
Pourquoi on a choisi ces briques, parce que la plupart sont open-source. Lien fort avec UD-Viz, développé en interne au LIRIS. L'idée est de mettre à disposition l'outil dans le monde de la recherche et permettre l'utilisation par différents acteurs privé et publique qui peuvent collaborer à l'élaboration du projet.

Ce qu'on doit enregistrer pour la slide:

- Image d'une arborescance globale
- Liens entre les briques (en gros : THREE -> Itowns -> UD-Viz -> IMUV).
- Zoom sur les différentes parties avec de breves explications.
- Liens des sites :
    - THREE.js - https://threejs.org/
    - Itowns (IGN) - https://www.itowns-project.org/
    - UD-Viz (LIRIS) - https://ud-viz.vcityliris.data.alpha.grandlyon.com/
    - Jitsi - https://jitsi.org/
    - Whitebophir - https://github.com/lovasoa/whitebophir
    - Parse - https://parseplatform.org/
    - Mongodb - https://www.mongodb.com/fr-fr

### Détaillez les principales solutions logicielles ou technologiques utilisées et les développements spécifiques réalisés

Ce qu'on doit enregistrer pour la vidéo:

- Image qui montre un front-end back-end
- Le github
- Image du jeu

Texte:

toutes les briques et modules enoncé precedement sont necessaire pour assurer le bon fonctionnement de notre solution logiciel imuv.
La solution logicielle proposée prend la forme d'une application web composé d'un front-end (javascript + webgl) et d'un back-end (nodejs) spécifique. C'est un outil collaboratif (multijoueur) immersif sous la forme d'un campus numérique dans un monde 3D persistant sur le web. 
Tout est disponible sur la plateforme Github (https://github.com/VCityTeam/UD-Imuv/) où on peut retrouver les deux projets npm (front et back). Participation au développement d'UD-Viz.


###  Précisez sur quels référentiels techniques, normes ou standards vous appuyez-vous (consortiums, groupes de travail) pour mettre en place le projet ?

Ce qu'on doit enregistrer pour la vidéo:

- Site du Labex
- Site du LIRIS
- Site de VCity 


Texte:

Projet initié par le Labex IMU. Collaboration avec les membres de la plateforme UD-SV/VCity (LIRIS). Responsabilité scientifique (JYT et GGE). Méthode agile (itératif), milestone trimestriel. Idée originale de JYT, GGE et DCH. Le projet à commencé avec Didier CHANFRAY, Yael BARROZ, Valentin MACHADO et Mathieu LIVEBARDON.


###  Montrez ensuite les principales fonctions de votre jumeau numérique, le processus collaboratif, les outils d'analyse, la valorisation des données, etc.

Ce qu'on doit enregistrer pour la vidéo:
- Gameplay
- Fonctionnalités
- Voir Scénario (en O)


Texte:quand on aura la vidéo

Commenter le gameplay. 

###  Indiquez d’où proviennent les données utilisées ? Par qui et comment sont collectées les données initiales et actualisées, à quelle fréquence et où sont-elles hébergées ?

Ce qu'on doit enregistrer pour la vidéo:

- Py3dtiler
- Site du GrandLyon
- Site de l'IGN (https://geoservices.ign.fr/telechargement)
- Image de l'ile / avatar / **ZEPPELYON** ouvert dans blender

Texte:

| Type                                                | Provenance      | Actualisé            | Hebergé           |
| --------------------------------------------------- | --------------- | -------------------- | ----------------- |
| Elecation Layer                                     | data grand lyon | //                   | //                |
| Fond de carte                                       | IGN             | //                   | //                |
| Lignes de bus, velov et zones humides               | data grand lyon | //                   | //                |
| 3Dtiles                                             | cityGML data grand lyon        2018       | py3dtilers (Lorenzo) | VPS OVH           |
| Modeles 3D (iles, salles, avatar, zeppelin, spiral) | Yael Barroz     | //                   | VPS OVH           |
| Modeles 3D (souris)                                 | Internet        | //                   | VPS OVH           |
| Donnée utilisateur                                  | imuvirtuel.fr   | //                   | VPS OVH (mongodb) |



Externe et interne. Externe : IGN, data grand lyon Interne : py3dtiler, gltf (yaël) 





###  Indiquez à nouveau qui sont les gestionnaires, utilisateurs et les bénéficiaires. Quels sont leurs rôles dans le fonctionnement ?

La communauté open-source, les acteurs urbains, les partenaires d'IMU, les citoyens intéressés par les questions d'urbanisme, le monde de la recherche **urbaine**.

**Comment by mathieuLivebardon** [comment]
The video has been produced and the application has been validated, the video is [here](https://www.twinplus.fr/vods/8bb8b983-96c4-ed11-9f73-6045bd8890e4)
