### ISSUE TITLE
Circulation over the flying campus

### ISSUE THREAD

**Issue by valentinMachado** [VCityTeam/UD-Imuv#47]
place collision + teleporter + rework of the map

**Comment by mathieuLivebardon** [comment]
![ksnip_20211103-160538](https://user-images.githubusercontent.com/34244904/140087360-06dc9fee-a46d-49bb-ad46-ead61f87c84b.png)
Monter les spirales en haut des escaliers

**Comment by mathieuLivebardon** [comment]
Delete the teleporter of the island of the "gros caillou"
