### ISSUE TITLE
BBB client integration

### ISSUE THREAD

**Issue by valentinMachado** [VCityTeam/UD-Imuv#50]
User story : As a player, I want to chat, talk with other players, so that working interactions become natural.
- [x] Integrate BBB client in iframe (overlay)
- [x] Create a BBB room for each world/room
- [ ] Assert BBB integration is deployment compatible: 
   * Audio and video sometimes cannot be requested on rict2, certainly due to the HTTP context.
   * Depends on: 
        * #12 
        * #50 
        * #113 

## Prospective
- [ ] Create BBB based interactive areas (a part of world game object)

**Comment by valentinMachado** [comment]
still problem of sync between bbb server and imuv server (its gives outdated url to client). Rooms on the bbb server seems to close themselves after a client connexion.

sometimes the bbb iframe cannot open

**Comment by valentinMachado** [comment]
audio and video sometimes connot be requested on rict2 certainly due to the http context.
when deploying on ovh server with an https url test to see if it's fix the problem

**Comment by valentinMachado** [comment]
depends of https://github.com/VCityTeam/UD-Imuv/issues/12

**Comment by mathieuLivebardon** [comment]
ooooooooooooooooooooooooooooooooold
