### ISSUE TITLE
First animations

### ISSUE THREAD

**Issue by valentinMachado** [VCityTeam/UD-Imuv#59]
depend of this https://github.com/VCityTeam/UD-Viz/issues/208

- [x] wind mill
- [x] helix zeppelin 

Windsock animation and zeppelin move in this issue : https://github.com/VCityTeam/UD-Imuv/issues/120

**Comment by mathieuLivebardon** [comment]
First animation in https://github.com/VCityTeam/UD-Imuv/tree/renderdata
