### ISSUE TITLE
display an image stream on the avatar

### ISSUE THREAD

**Issue by valentinMachado** [VCityTeam/UD-Imuv#60]

**Comment by mathieuLivebardon** [comment]
![ksnip_20211103-162012](https://user-images.githubusercontent.com/34244904/140089837-7f384ba0-5ade-40db-abfe-4556fbab2599.png)
The three models in the flying campus (random color)

**Comment by mathieuLivebardon** [comment]
![2021-11-15_16h24_26](https://user-images.githubusercontent.com/34244904/141807943-215b4a2e-e4e6-4fe1-9fe2-c887c5cf5e61.png)
Texture on Face
