### ISSUE TITLE
Assets storage and synchronization

### ISSUE THREAD

**Issue by valentinMachado** [VCityTeam/UD-Imuv#75]
- [ ] Discover best practices (GIT LFS. Hosted on VPS, ...)
      - Is versioning needed ?
      - When assets retrieved : at build time or at run time ?
- [ ] Choose the type of assets handling
- [x] #153

## Notes
* LIRIS' gitlab server offers [git-lfs](https://docs.gitlab.com/ee/topics/git/lfs/) support (go to settings/general of each project)
* Commands to [estimate the size of a git repository](https://stackoverflow.com/questions/8185276/find-size-of-git-repository): `git count-objects -vH` and/or `git bundle create tmp.bundle --all && du -sh tmp.bundle`.  
   As of Tue Apr 26 (commit 8110d3161b), the respective answers for this UD-Imuv repository are respectively and `435.82 MiB` and `440M`.  
   And `du -sh UD-Imuv/client/assets/* | grep 'M' | sort -rn` yields
   ```bash
   488M   UD-Imuv/client/assets/3DTiles
    77M   UD-Imuv/client/assets/videos
    45M   UD-Imuv/client/assets/models
    17M   UD-Imuv/client/assets/img
     3.6M	UD-Imuv/client/assets/sounds
     ...   more stuff with Kb sizes 
   ```
   Hence assuming
     * the maximum size of a github repo should be of 1G,
     * assuming the 3DTiles, videos, images and sounds won't be edited (only possibly extended with new elements) and only the models could change,
     * the size of the models won't get bigger thant 80M
     * a zero compression ratio for the models
     
  there is roughly `(1000-450)/80 ~= 6` more opportunities to update the models before reaching github's repository limit.
* If we wish to find some "room" we can always remove the 3DTiles tilesets from the repository and use the exat same ones (and build time or run time) encountered at [Liris dataset](https://dataset-dl.liris.cnrs.fr/three-d-tiles-lyon-metropolis/)

**Comment by mathieuLivebardon** [comment]
* Git limit : No real limit but we should follow this *rule of thumb* : 1GB per repository, 100MB per file. Source : https://stackoverflow.com/questions/3230721/max-file-size-and-max-repository-size-in-git
* File size limit GitHub : ***Warning >50 MB*** ; ***Block > 100 MB***. Source : https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github
* GitHub + Git LFS : ***Maximum File Size > 2 GB***. Source : https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-git-large-file-storage
* Why not store assets with git ? : https://softwareengineering.stackexchange.com/questions/80962/should-images-be-stored-in-a-git-repository ; https://stackoverflow.com/questions/28028868/what-should-one-do-with-media-assets-related-to-a-git-repository
